/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.0.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as actions_playComputerMove from "../actions/playComputerMove";
import type * as createGame from "../createGame";
import type * as getGame from "../getGame";
import type * as getOptions from "../getOptions";
import type * as playComputerMove from "../playComputerMove";
import type * as playMove from "../playMove";
import type * as voteForOption from "../voteForOption";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "actions/playComputerMove": typeof actions_playComputerMove;
  createGame: typeof createGame;
  getGame: typeof getGame;
  getOptions: typeof getOptions;
  playComputerMove: typeof playComputerMove;
  playMove: typeof playMove;
  voteForOption: typeof voteForOption;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
