/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.6.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as actions_playComputerMove from "../actions/playComputerMove";
import type * as createGame from "../createGame";
import type * as getGame from "../getGame";
import type * as getOptions from "../getOptions";
import type * as playComputerMove from "../playComputerMove";
import type * as playMove from "../playMove";
import type * as voteForOption from "../voteForOption";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  "actions/playComputerMove": typeof actions_playComputerMove;
  createGame: typeof createGame;
  getGame: typeof getGame;
  getOptions: typeof getOptions;
  playComputerMove: typeof playComputerMove;
  playMove: typeof playMove;
  voteForOption: typeof voteForOption;
}>;
