import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ConvexProvider, ConvexReactClient } from "convex-dev/react";
import convexConfig from "../convex.json";
import { useQuery, useMutation, useConvex } from "../convex/_generated";
import { useState, useEffect } from 'react';
import chess from "chess";
import { constructGame } from '../common';



const convex = new ConvexReactClient(convexConfig.origin);


const whitePieceToString = {
  pawn: "♙",
  rook: "♖",
  knight: "♘",
  bishop: "♗",
  queen: "♕",
  king: "♔",
};
const blackPieceToString = {
  pawn: "♟",
  rook: "♜",
  knight: "♞",
  bishop: "♝",
  queen: "♛",
  king: "♚",
};

const ChessSquare = ({piece, index}: {piece: chess.Piece, index: number}) => {
  const isWhite = piece && piece.side.name === "white";
  const pieceStr = piece ? (isWhite ? whitePieceToString[piece.type] : blackPieceToString[piece.type]) : "";
  const colorClass = piece ? (isWhite ? styles.whitepiece : styles.blackpiece) : undefined;
  const row = Math.floor(index / 8);
  const col = index % 8;
  const squareColorClass = ((row + col) % 2 === 0) ? styles.whitesquare : styles.blacksquare;
  return <div className={styles.griditem + " " + squareColorClass}>
    <span className={colorClass}>{pieceStr}</span>
  </div>;
}

const ChessBoard = () => {
  const game = useQuery("getGame");
  const createGame = useMutation("createGame");
  useEffect(() => {
    if (game === null) {
      createGame();
    }
  })
  if (!game) {
    return null;
  }
  const [moves, gameState] = game;
  const gameClient = constructGame(gameState, moves);
  // TODO: display move history?
  const board = gameClient.game.board;
  const squares = board.squares;

  // Reorder squares so rank 1 is at the bottom.
  for (let rank = 0; rank < 4; rank++) {
    const swapRank = 7 - rank;
    for (let file = 0; file < 8; file++) {
      const index = rank * 8 + file;
      const swapIndex = swapRank * 8 + file;
      const temp = squares[swapIndex];
      squares[swapIndex] = squares[index];
      squares[index] = temp;
    }
  }

  return (<div className={styles.gridcontainer}>
    {squares.map((square, i) => <ChessSquare key={i} piece={square.piece} index={i} />)}
  </div>);
};

const EntryForm = () => {
  const options = useQuery("getOptions") ?? [];
  const voteForOption = useMutation("voteForOption");
  const [moveInput, setMoveInput] = useState("");
  const playMove = useMutation("playMove");
  const handleInputChange = (event: any) => {
    setMoveInput(event.target.value);
  };
  const submit = () => {
    voteForOption(moveInput);
  };
  const play = () => {
    playMove();
  }
  return (<div>
    <p>
      Enter moves in algebraic notation like Bxe5.
      Only the top voted move can be played.
      Invalid moves are ignored.
      Special instructions "undo" and "resign" must be unanimous.
    </p>
    <ul>
      {options.map(option => <li key={option.move}>{option.move}: {option.votes} votes</li>)}
    </ul>
    <input type="text" onChange={handleInputChange} value={moveInput} />
    <button onClick={submit}>Vote</button>
    <div><button onClick={play}>Play Top Move</button></div>
  </div>);
};

const PlayChess = () => {
  return (
    <div>
      <ChessBoard />
      <EntryForm />
    </div>
  );
};


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Convex Plays</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Convex Plays Chess
        </h1>

        <ConvexProvider client={convex}>
          <PlayChess />
        </ConvexProvider>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
